#!/bin/bash


python split.py coco_train split
python split.py coco_dev split

#python data_to_conll.py --input pre_coco_train.json --output coco_train.conll --train True

#--input:  processed data generated by split.py
#--output: desired output
#--train : determine whether the file is used for training or not



