#!/bin/bash


python split.py split coco_train 
python split.py split coco_dev   

#python data_to_conll.py --input pre_coco_train.json --output coco_train.conll --train True

#--input:  processed data generated by split.py
#--output: desired output
#--train : determine whether the file is used for training or not



